accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('myprofile/', views.myprofile, name='myprofile'),
    # path('login/', views.Login.as_view(), name='login'),
    # path('signup/', views.Signup.as_view(), name='signup'),

]

matching_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plans.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('message/', include('message.urls')),
    path('purchase_history/', include('purchase_history.urls')),
]

message/urls.py
from django.urls import path
from . import views

app_name = 'message'

urlpatterns = [
    path('message_history/', views.message_history, name='message_history'),
]

plans/urls.py
from django.urls import path
from . import views

app_name = 'plans'

urlpatterns = [
    path('', views.index, name="index"),
    path('product_list/', views.product_list, name='product_list'),
    path('create_product/', views.create_product, name='create_product'),
]

purchase_history/urls.py
from django.urls import path
from . import views

app_name = 'purchase_history'

urlpatterns = [
    path('purchase_history_list/', views.purchase_history_list,
         name='purchase_history_list'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    """拡張ユーザーモデル"""

    class Meta:
        verbose_name_plural = 'CustomUser'

message/models.py
from django.db import models

# Create your models here.

plans/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Product(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    product_text = models.TextField()
    price = models.PositiveIntegerField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

purchase_history/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model  # ユーザーモデルを取得するため
from .models import CustomUser
from allauth.account.forms import LoginForm, SignupForm

# # ユーザーモデル取得
# User = get_user_model()


# '''ログイン用フォーム'''


class MyLoginForm(LoginForm):

    # bootstrap4対応
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label


'''サインアップ用フォーム'''


class MySignupForm(SignupForm):

    # class meta:
    #     model = CustomUser
    #     fields = ('last_name', 'first_name', 'email', 'username',)

    def __init__(self, *args, **kwargs):

        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['required'] = ''

            # オートフォーカスとプレースフォルダーの設定

            print(field.label)
            if field.label == '姓':
                field.widget.attrs['autofocus'] = ''
                field.widget.attrs['placeholder'] = '田中'
            elif field.label == '名':
                field.widget.attrs['placeholder'] = '一郎'
            elif field.label == 'メールアドレス':
                field.widget.attrs['placeholder'] = '***@gmail.com'

plans/forms.py
from . import models
from . import forms


class ProductForm(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ('title', 'product_text', 'price', 'author',
                  'create_date', 'published_date', )
        labels = {'title': '商品名', 'product_text': '説明文', 'price': '値段',
                  'author': 'ユーザー', 'create_date': '作成日', 'published_date': '公開日', }

accounts/views.py
from django.shortcuts import render, resolve_url
# from .forms import LoginForm, SignupForm
# from django.contrib.auth.views import LoginView
# vfrom django.views import generic
#from django.contrib.auth.mixins import UserPassesTestMixin
#from django.views.generic import DetailView
#from .models import CustomUser

'''プロフィール画面'''


def myprofile(request):
    return render(request, 'accounts/myprofile.html')


'''いつかプロフィールを制限する機能を実装する'''
# class OnlyYouMixin(UserPassesTestMixin):
#    raise_exception = False     # set True if raise 403_Forbidden

#    def test_func(self):
#        user = self.request.user
#        return user.pk == self.kwargs['pk'] or user.is_superuser


# class MyprofileView(OnlyYouMixin, DetailView):
#    model = CustomUser
#    template_name = 'accounts/myprofile.html'

#    def get_context_data(self, **kwargs):
#        context = super().get_context_data(**kwargs)
#        pass  # 必要に応じて処理を追加
#        return context

# '''ログイン'''


# class Login(LoginView):
#     from_class = LoginForm
#     template_name = 'account/login.html'


# '''サインアップ'''


# class Signup(generic.CreateView):
#     template_name = 'account/signup.html'
#     form_class = SignupForm

#     def form_valid(self, form):
#         user = form.save()
#         return redirect('account:signup_done')

#     # データ送信
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["process_name"] = "Sign up"
#         return context

message/views.py
from django.shortcuts import render

# Create your views here.


def message_history(request):
    return render(request, 'message/message_history.html')

plans/views.py
from django.shortcuts import render
from .models import Product


# Create your views here.


def index(request):
    return render(request, 'plans/index.html')


def product_list(request):
    products = Product.objects.all()
    return render(request, 'plans/product_list.html', {'products': products})


def create_product(request):
    return render(request, 'plans/create_product.html')

purchase_history/views.py
from django.shortcuts import render

# Create your views here.


def purchase_history_list(request):
    return render(request, 'purchase_history/purchase_history_list.html')

accounts/templates/accounts/email_confirm.html
{% extends 'base.html' %}

{% block title %}Confirm sign up{% endblock %}

{% block active_signup %}active{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="my-div-style">
      <h1>ユーザー登録</h1>

      {% if confirmation %}
      <p>ユーザー登録を確定するには、以下のボタンを押してください。</p>

      <form method="post" action="{% url 'accounts_confirm_email' confirmation.key %}">
        {% csrf_token %}
        <button class="btn btn-primary" type="submit">確定</button>
      </form>
      {% else %}
      {% url 'accounts_email' as email_url %}

      <p>リンクの有効期限が過ぎています。<a href="{{email_url}}">再申請</a>.</p>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Log In{% endblock %}

{% block active_login %}active{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="my-div-style">
      <h1>Log In</h1>
      <form method="post" action="{% url 'accounts_login' %}">
        {% csrf_token %}

        {{ form.as_p }}

        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}

        <button class="btn btn-primary" type="submit">ログイン</button>
        <p><a class="button secondaryAction" href="{% url 'aacounts_reset_password' %}">パスワードを忘れましたか</a></p>
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/myprofile.html
{% extends 'plans/base.html' %}

{% block content %}
<h1>Hello</h1>
{% endblock %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}

{% block title %}パスワードリセット{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="my-div-style">
      <h1>パスワードリセット</h1>
      {% if user.is_authenticated %}
      {% include "accounts/snippets/already_logged_in.html" %}
      {% endif %}

      <p>パスワードリセット用メールを送信します。</p>
      <form method="post" action="{% url 'accounts_login' %}">
        {% csrf_token %}

        {{ form.as_p }}

        <button class="btn btn-primary" type="submit">送信</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password reset done{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="my-div-style">
      <h1>パスワードリセット</h1>
      {% if user.is_authenticated %}
      {% include "accounts/snippets/already_logged_in.html" %}
      {% endif %}

      <p>パスワードリセット用メールを送信しました。</p>
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/password_reset_from_key.html
{% extends 'base.html' %}

{% block title %}パスワードリセット{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="my-div-style">
      <h1>{% if token_fail %}不正トークン{% else %}パスワードリセット{% endif %}</h1>
      {% if token_fail %}
      {% url 'accounts_reset_password' as passwd_reset_url %}
      <p>このパスワードリセット用リンクは無効になっています。<a href="{ passwd_reset_url }">パスワードリセット再申請</a></p>
      {% else %}
      {% if form %}
      <form method="POST" action="{{ action_url }}">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary" type="submit">変更</button>
      </form>
      {% else %}
      <p>パスワードは変更されています。</p>
      {% endif %}
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block title %}サインアップ{% endblock %}

{% block active_signup %}active{% endblock %}

{% block contents %}
<div class="container">
  <div class="row">
    <div class="my-div-style">
      <h1>サインアップ</h1>
      <form method="post" action="{% url 'accounts_signup' %}">
        {% csrf_token %}

        {{forms.as_p}}

        {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
        {% endif %}
      </form>
    </div>
  </div>
</div>

{% endblock %}

message/templates/message/message_history.html
{% extends 'plans/base.html' %}

{% block content %}
<h1>Hello</h1>
{% endblock %}

plans/templates/plans/base.html
{% load static %}
<html>

<head>
  <title>コメディカルによるコメディカルのためのオンライン家庭教師</title>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
  <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="{% static 'css/plans.css' %}">
</head>

<body>
  <div class="page-header">
    <h1><a href="/">コメディカルによるコメディカルのためのオンライン家庭教師</a></h1>
    {% if not user.is_authenticated %}
    <p><a href="{% url 'account_login' %}">ログイン</a></p>
    <p><a href="{% url 'account_signup' %}">ユーザー登録</a></p>
    {% else %}
    <p><a href="{% url 'account_logout' %}">ログアウト</a> </p>
    {% endif %}
  </div>
  <div class="pl-4 small" style="background-color: #e2e3e5 ; border-bottom: solid 1px #f3f3f3;">
    {% if not user.is_authenticated %}
    こんにちは！ ゲスト さん
    {% else %}
    こんにちは！ {{ user.username }} さん
    {% endif %}
  </div>
  <div class="content container">
    <div class="row">
      <div class="col-md-8">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
</body>

</html>

plans/templates/plans/create_product.html
{% extends 'plans/base.html' %}




{% block content %}
<div>
  <h1>商品の作成</h1><br>

  <form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
</div>

{% endblock %}

plans/templates/plans/index.html
{% extends 'plans/base.html' %}




{% block content %}
<h1><a href="product_list">授業プラン一覧</a></h1>
<h1><a href="accounts/myprofile">マイページ</a></h1>
<h1><a href="message/message_history">メッセージ履歴</a></h1>
<h1><a href="purchase_history/purchase_history_list">購入履歴</a></h1>
{% endblock %}

plans/templates/plans/product_list.html
{% extends 'plans/base.html' %}

{% block content %}
<h1><a href={% url "plans:create_product" %}>授業プランを作る</a></h1>
{% for product in products %}
<!---商品自体の表示・非表示でifを作る-->
<div>
  <p>date: {{ product.created_date }}</p>
  <h1><a href="">title: {{ product.title }}</a></h1>
  <p>{{ product.text|linebreaksbr }}</p>
  <p>{{ product.price|linebreaksbr }}</p>
  <hr>
</div>
{% endfor %}


{% endblock %}

purchase_history/templates/purchase_history/purchase_history_list.html
{% extends 'plans/base.html' %}

{% block content %}
<h1>Hello</h1>
{% endblock %}